/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../components/categories/index`; params?: Router.UnknownInputParams; } | { pathname: `/../components/categories/styles`; params?: Router.UnknownInputParams; } | { pathname: `/../components/caterogy/styles`; params?: Router.UnknownInputParams; } | { pathname: `/../components/caterogy/index`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/categories/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/categories/styles`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/caterogy/styles`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/caterogy/index`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/home${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/../components/categories/index${`?${string}` | `#${string}` | ''}` | `/../components/categories/styles${`?${string}` | `#${string}` | ''}` | `/../components/caterogy/styles${`?${string}` | `#${string}` | ''}` | `/../components/caterogy/index${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../components/categories/index`; params?: Router.UnknownInputParams; } | { pathname: `/../components/categories/styles`; params?: Router.UnknownInputParams; } | { pathname: `/../components/caterogy/styles`; params?: Router.UnknownInputParams; } | { pathname: `/../components/caterogy/index`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
